// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.poxiao.protobuf;

public final class UserProtobuf {
  private UserProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface userBufOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 ID = 1;
    boolean hasID();
    int getID();
    
    // required string Url = 2;
    boolean hasUrl();
    String getUrl();
    
    // required bool IsSD = 3;
    boolean hasIsSD();
    boolean getIsSD();
  }
  public static final class userBuf extends
      com.google.protobuf.GeneratedMessage
      implements userBufOrBuilder {
    // Use userBuf.newBuilder() to construct.
    private userBuf(Builder builder) {
      super(builder);
    }
    private userBuf(boolean noInit) {}
    
    private static final userBuf defaultInstance;
    public static userBuf getDefaultInstance() {
      return defaultInstance;
    }
    
    public userBuf getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poxiao.protobuf.UserProtobuf.internal_static_protobuf_userBuf_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poxiao.protobuf.UserProtobuf.internal_static_protobuf_userBuf_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 ID = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    public boolean hasID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getID() {
      return iD_;
    }
    
    // required string Url = 2;
    public static final int URL_FIELD_NUMBER = 2;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool IsSD = 3;
    public static final int ISSD_FIELD_NUMBER = 3;
    private boolean isSD_;
    public boolean hasIsSD() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getIsSD() {
      return isSD_;
    }
    
    private void initFields() {
      iD_ = 0;
      url_ = "";
      isSD_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSD()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, iD_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isSD_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isSD_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.poxiao.protobuf.UserProtobuf.userBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.poxiao.protobuf.UserProtobuf.userBuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.poxiao.protobuf.UserProtobuf.userBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poxiao.protobuf.UserProtobuf.internal_static_protobuf_userBuf_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poxiao.protobuf.UserProtobuf.internal_static_protobuf_userBuf_fieldAccessorTable;
      }
      
      // Construct using com.poxiao.protobuf.UserProtobuf.userBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        iD_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isSD_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poxiao.protobuf.UserProtobuf.userBuf.getDescriptor();
      }
      
      public com.poxiao.protobuf.UserProtobuf.userBuf getDefaultInstanceForType() {
        return com.poxiao.protobuf.UserProtobuf.userBuf.getDefaultInstance();
      }
      
      public com.poxiao.protobuf.UserProtobuf.userBuf build() {
        com.poxiao.protobuf.UserProtobuf.userBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.poxiao.protobuf.UserProtobuf.userBuf buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.poxiao.protobuf.UserProtobuf.userBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.poxiao.protobuf.UserProtobuf.userBuf buildPartial() {
        com.poxiao.protobuf.UserProtobuf.userBuf result = new com.poxiao.protobuf.UserProtobuf.userBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isSD_ = isSD_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poxiao.protobuf.UserProtobuf.userBuf) {
          return mergeFrom((com.poxiao.protobuf.UserProtobuf.userBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.poxiao.protobuf.UserProtobuf.userBuf other) {
        if (other == com.poxiao.protobuf.UserProtobuf.userBuf.getDefaultInstance()) return this;
        if (other.hasID()) {
          setID(other.getID());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasIsSD()) {
          setIsSD(other.getIsSD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasID()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasIsSD()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              iD_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              url_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isSD_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 ID = 1;
      private int iD_ ;
      public boolean hasID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getID() {
        return iD_;
      }
      public Builder setID(int value) {
        bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
        return this;
      }
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = 0;
        onChanged();
        return this;
      }
      
      // required string Url = 2;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
      }
      
      // required bool IsSD = 3;
      private boolean isSD_ ;
      public boolean hasIsSD() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsSD() {
        return isSD_;
      }
      public Builder setIsSD(boolean value) {
        bitField0_ |= 0x00000004;
        isSD_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsSD() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isSD_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.userBuf)
    }
    
    static {
      defaultInstance = new userBuf(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.userBuf)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_userBuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_userBuf_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\010protobuf\"0\n\007userBuf\022\n\n\002ID\030" +
      "\001 \002(\005\022\013\n\003Url\030\002 \002(\t\022\014\n\004IsSD\030\003 \002(\010B#\n\023com." +
      "poxiao.protobufB\014UserProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_userBuf_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_userBuf_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_userBuf_descriptor,
              new java.lang.String[] { "ID", "Url", "IsSD", },
              com.poxiao.protobuf.UserProtobuf.userBuf.class,
              com.poxiao.protobuf.UserProtobuf.userBuf.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
